version: '3.5'

services:

  limesurvey:
    image: acspri/limesurvey:5.3.9
    expose:
      - 80
    environment:
      - LIMESURVEY_DB_PASSWORD
      - LIMESURVEY_ADMIN_USER
      - LIMESURVEY_ADMIN_PASSWORD
      - LIMESURVEY_ADMIN_NAME
      - LIMESURVEY_ADMIN_EMAIL
      - VIRTUAL_HOST
      - VIRTUAL_PORT
      - LETSENCRYPT_HOST
      - LETSENCRYPT_EMAIL
    networks:
      - default
      - proxy
    volumes:
      - plugins:/var/www/html/plugins
      - upload:/var/www/html/upload
      - config:/var/www/html/application/config

  mysql:
    image: mariadb:10.7.3
    environment:
      - MYSQL_ROOT_PASSWORD
    volumes:
      - db:/var/lib/mysql

volumes:
  db:
  plugins:
  upload:
  config:

networks:
  proxy:
    external: true

