---

- name: "Set timezone to Europe/Berlin"
  timezone:
    name: "Europe/Berlin"

- name: "Update apt cache"
  apt:
    update_cache: true
    cache_valid_time: 3600
  when:
    - ansible_os_family == 'Debian'

- name: "Install packages"
  package:
    name:
      - "neovim"
      - "tmux"
    state: "present"
