---
dependencies: []
galaxy_info:
  role_name: basic
  author: Jan Otto
  description: Basic setup.
  license: "license (MIT)"
  min_ansible_version: 2.4
  platforms:
    - name: Ubuntu
      versions:
        - all
    - name: Debian
      versions:
        - all
  galaxy_tags: []
