---

name: "CI"

on:
  workflow_dispatch:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"

env:
  python_version: "3.9"

jobs:
  test:
    name: "Molecule"
    runs-on: "ubuntu-latest"
    strategy:
      matrix:
        distro:
          - "debian10"

    steps:
      - name: "Check out the codebase"
        # see https://github.com/marketplace/actions/checkout
        uses: "actions/checkout@v2"

      - name: "Set up Python"
        # see https://github.com/marketplace/actions/setup-python
        uses: "actions/setup-python@v2"
        with:
          python-version: "${{ env.python_version }}"

      - name: "Cache Python packages"
        # see https://github.com/marketplace/actions/cache
        uses: "actions/cache@v2"
        env:
          cache_name: "pip"
        with:
          path: "~/.cache/pip"
          key: "${{ runner.os }}-${{ env.cache_name }}-${{ hashFiles('**/requirements.txt') }}"
          restore-keys: |
            ${{ runner.os }}-${{ env.cache_name }}-

      - name: "Install Python dependencies"
        run: | 
          python -m pip install wheel
          python -m pip install --no-deps --requirement requirements.txt

      - name: "Install galaxy roles"
        run: "ansible-galaxy install --role-file requirements.yml"

      - name: "(Workaround) Remove all identities except of dev from vault_identity_list"
        # See https://github.com/marketplace/actions/find-and-replace
        uses: "jacobtomlinson/gha-find-replace@master"
        with:
          find: "vault_identity_list.*"
          replace: "vault_identity_list = dev@.vault-pass.dev"
          include: "ansible.cfg"

      - name: "Run Molecule tests"
        env:
          PY_COLORS: "1"
          ANSIBLE_FORCE_COLOR: "1"
          MOLECULE_DISTRO: "${{ matrix.distro }}"
        run: "molecule test"
